mutation CreateAssetUpload($input: CreateAssetUploadInput!) {
  createAssetUpload(input: $input) {
    upload {
      asset {
        id
        status
        createdAt
      }
      uploadUrl
      headers {
        name
        value
      }
    }
    userErrors {
      code
      message
      path
    }
  }
}

query Asset($id: UUID!) {
  asset(id: $id) {
    id
    status
    url
  }
}

mutation DeleteAsset($input: DeleteAssetInput!) {
  deleteAsset(input: $input) {
    success
    userErrors {
      code
      message
      path
    }
  }
}
