import { StyleSheet } from 'react-native-unistyles';

export const styles = StyleSheet.create((theme, runtime) => ({
  root: {
    alignItems: 'flex-end',
    backgroundColor: theme.colors.background,
    borderTopColor: theme.colors.border,
    borderTopWidth: 1,
    flexDirection: 'row',
    gap: theme.spacing.sm,
    padding: theme.spacing.md,
    paddingBottom: Math.max(theme.spacing.md, runtime.insets.bottom),
  },
  input: {
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: theme.radii.md,
    borderWidth: 1,
    color: theme.colors.text,
    flex: 1,
    fontSize: 16,
    lineHeight: 22,
    maxHeight: 132,
    minHeight: 48,
    paddingHorizontal: theme.spacing.lg,
    paddingVertical: theme.spacing.md,
  },
  placeholder: { color: theme.colors.textMuted },
  iconButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.surface,
    borderColor: theme.colors.border,
    borderRadius: theme.radii.md,
    borderWidth: 1,
    height: 48,
    justifyContent: 'center',
    minWidth: 48,
    paddingHorizontal: theme.spacing.sm,
  },
  iconLabel: { color: theme.colors.text, fontSize: 13, fontWeight: '500' },
  sendButton: {
    alignItems: 'center',
    backgroundColor: theme.colors.primary,
    borderRadius: theme.radii.md,
    height: 48,
    justifyContent: 'center',
    minWidth: 60,
    paddingHorizontal: theme.spacing.md,
  },
  sendLabel: { color: theme.colors.primaryText, fontSize: 14, fontWeight: '600' },
  pressed: { opacity: 0.72 },
  offline: {
    backgroundColor: theme.colors.surfaceMuted,
    color: theme.colors.textMuted,
    fontSize: 13,
    padding: theme.spacing.sm,
    textAlign: 'center',
  },
  draftStatus: {
    color: theme.colors.textMuted,
    fontSize: 13,
    padding: theme.spacing.sm,
    textAlign: 'center',
  },
  attachment: {
    alignItems: 'center',
    backgroundColor: theme.colors.background,
    flexDirection: 'row',
    gap: theme.spacing.md,
    paddingHorizontal: theme.spacing.lg,
    paddingTop: theme.spacing.sm,
  },
  thumbnail: { borderRadius: theme.radii.md, height: 64, width: 64 },
  removeButton: { minHeight: 44, justifyContent: 'center' },
  removeLabel: { color: theme.colors.danger, fontSize: 14, fontWeight: '700' },
  assetStatus: { flex: 1, gap: theme.spacing.xs },
  statusLabel: { color: theme.colors.textMuted, fontSize: 13 },
  retryButton: { alignSelf: 'flex-start', minHeight: 44, justifyContent: 'center' },
  retryLabel: { color: theme.colors.primary, fontSize: 14, fontWeight: '700' },
}));
